### ISSUE TITLE
PHP 8.1 Compatibility?

### ISSUE THREAD

**Issue by azrek** [taq/phpreports#7]
Hi @taq  ,

Happy New Year! 
I'm wondering if there are any plans to upgrade this library to PHP 8.1?
It's a great tool and I hope it will continue.
Thank you.
Ghada

**Comment by taq** [comment]
Hi! Happy New Year!

I'm not really sure. I'm not using PHP anymore. Would love to have more time to take a look on it again.

**Comment by azrek** [comment]
hi @taq 

Thank you very much for the quick response.
I guess we won't wait ... 

Cheers,
Ghada

**Comment by taq** [comment]
Hey @azrek 

Won't wait? Will make a fork? Feel free to keep it going. :-)

**Comment by azrek** [comment]
hi @taq 

I'd love to but I don't program much these days. I can code review for you though !

Cheers.

**Comment by taq** [comment]
Ok, so, let's try to give some traction between user/developer. I didn't run it on PHP 8.1, why it is not compatible? Tell me what are the failing points.

**Comment by azrek** [comment]
hi @taq 
We haven't upgraded yet. I'm just doing the due diligence/preliminary checks to see which libraries will be affected.
Upgrade won't start for a few weeks - I'm sorry I'm not much help. 
Cheers.

**Comment by taq** [comment]
Ok, but how do you know it won't work on 8.1? 🙂

**Comment by EthraZa** [comment]
Just to add my 2 cents, I'm using it on 7.4.20 so, the chances to work on 8.x are good.

**Comment by azrek** [comment]
hi @taq  and @EthraZa 

I was going through the pull requests and notes. I only saw that it's compatible up to 7.1: (i.e. pull request 1)

https://github.com/taq/phpreports/pull/1

It's great to hear it's compatible with PHP 7.4.20! That is great news for 8.1.

I'm sorry - I really don't mean to harass you.

Cheers.

**Comment by taq** [comment]
@EthraZa thanks for the feedback!

@azrek no problem! I'm happy to know it's still working on recent PHP versions. No harassing at all.

Let's do this: if it won't work with PHP 8.1 (I suppose you'll test it before going to production, right?) send me what happens on another issue and I'll try to take a look. Meanwhile, I'll close this issue here.

Nowadays I have less free time than when I created this project, but if it stop working with new versions, we can see what we can do about it.

**Comment by azrek** [comment]
Thank you @taq and @EthraZa  - I will keep you updated.

Have a great day!

Cheers.
